import React from 'react';

const AIBanner = ({ type = 'medical', onClose, className = 'p-4 mb-6' }) => {
  const isSupport = type === 'support';

  return (
    <div className={`bg-gradient-to-r from-amber-50 to-orange-50 border border-amber-200 rounded-xl shadow-sm flex gap-4 animate-fade-in relative ${className}`}>
      <div className="flex-shrink-0">
        <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
      </div>
      <div className="flex-1 pr-6 text-left">
        <h4 className="text-sm font-bold text-amber-900">
          {isSupport ? 'AI Assistant Notice' : 'AI-Generated Content Notice'}
        </h4>
        <p className="text-sm text-amber-800 mt-1">
          {isSupport 
            ? 'This assistant is powered by AI to help you navigate our services. It should not be used for medical advice or diagnostic purposes.'
            : <>This summary has been generated by an AI assistant. While designed to be helpful, it may contain inaccuracies and should <span className="font-bold underline">not</span> be used as a substitute for professional medical judgment. Always consult with your treating physician regarding your health records.</>
          }
        </p>
      </div>
      {onClose && (
        <button 
          onClick={onClose} 
          className="absolute top-3 right-3 text-amber-500 hover:text-amber-700 transition-colors p-1"
          aria-label="Close warning"
          type="button"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      )}
    </div>
  );
};

export default AIBanner;
